# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AggroEats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
