# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twotter', '0008_auto_20160428_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='twoot',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twoot',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='twotter.TwotterProfile'),
        ),
    ]
